spring.application.name=prode-airfibra-mundial-2026
server.servlet.context-path=/prode-airfibra
server.port=8080
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=60s

spring.profiles.active=dev

spring.datasource.url=jdbc:mysql://localhost:3306/prode_airfibra_mundial?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Buenos_Aires
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# JPA
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/Buenos_Aires
spring.jackson.time-zone=America/Argentina/Buenos_Aires
serverTimezone=America/Argentina/Buenos_Aires&useLegacyDatetimeCode=false

# JWT
jwt.secret=K2RadioMundial2026SecretKeyForJWTTokenGenerationMustBeLongEnough256Bits
# El token principal dura 1 dia
jwt.expiration=86400000
# El token de refresco dura 6 meses
jwt.refresh-expiration=15552000000
# jwt.refresh-expiration=604800000


app.frontend-url=http://localhost:3000
app.prediction-lock-hours=24


spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=shazminsolutions@gmail.com
#spring.mail.password=xbrtkcnutqqdqmap
spring.mail.username=fastbuild.dev@gmail.com
spring.mail.password=ceqzlnnshnfcyepq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
